   <?php 
   echo $this->headScript()
                ->prependFile($this->basePath() . '/sb-admin-v2/js/sb-admin.js')
                ->prependFile($this->basePath() . '/sb-admin-v2/js/plugins/metisMenu/jquery.metisMenu.js')
                ->prependFile($this->basePath() . '/sb-admin-v2/js/bootstrap.min.js')
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                ;
        ?>