<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/lib/moment/moment.min.js')
        ->appendFile($this->basePath() . '/lib/datetimepicker/js/bootstrap-datetimepicker.min.js')
        ->appendFile($this->basePath() . '/lib/moment/locale/es.js')
?>

<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/lib/datetimepicker/css/bootstrap-datetimepicker.min.css')
?> 

<br>
<div class="row container-fluid">
    <div class="col-lg-12 col-md-12 col-xs-12">
        
     <?php echo $this->partial('widget/contactFilter', array('form' => $this->contactFilter)); ?>    
    </div>
    
</div>

<?php echo $this->RenderBootstrapGrid($this->grid); ?>


<script>

    function dynamicFilter(item) {
        var val = $(item).val();
        var check = $(item).is(':checked');
 

        // alert(val+check);

        var neighborhoodActual = $('[name="neighborhood"]').val();

        if (val === "Ciudad Autónoma de Buenos Aires") {

            if (check) {
                $('[name="city"]').val(val);
            } else {
                $('[name="city"]').val("");
            }



        } else {


            if (check) {
                $('[name="neighborhood"]').val(neighborhoodActual + val + "|");
            } else {
                var neighborhoodActual = neighborhoodActual.replace(val + "|", "");
                $('[name="neighborhood"]').val(neighborhoodActual);
            }

        }
    }

</script>