<div class="row">


    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="collapseListGroupHeading1">
            <h4 class="panel-title">
                <a class="" data-toggle="collapse" href="#collapseListGroup1" aria-expanded="true" aria-controls="collapseListGroup1">
                    Despliegue de filtros
                </a>
            </h4>
        </div>
        <div id="collapseListGroup1" class="panel-collapse collapse " role="tabpanel" aria-labelledby="collapseListGroupHeading1" aria-expanded="true">

            <div class="panel-body">




                <?php
                $form = $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="row container-fluid">
                    <?php $multiplo = 2; ?>
                    <?php $countRow = 2; ?>
                        <?php $checkBoxRow = 4; ?>
                    <?php foreach ($form as $element) : ?>

                        <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
                                <?php echo $this->formElement($element); ?>
                                <?php break; ?>
                      <?php case "submit": ?>
                    
                    
                      <?php break; ?>
                    
                      <?php case "select": ?>

                                    <div class="row">
                                  

                                    <div class="col-lg-12 col-md-12 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>

                                            <div class="col-lg-10 col-md-10">
                                                <?php echo $this->formElement($element); ?>
                                                <?php if ($element->getOption('description')): ?>
                                                    <p class="help-block"><?php echo $element->getOption('description') ?></p>
                                                <?php endif; ?>
                                                <?php if ($this->formElementErrors($element)) : ?>
                                                    <?php
                                                    // Imprimo los errores
                                                    echo $this->formElementErrors()
                                                            ->setMessageOpenFormat('<span class="help-block">')
                                                            ->setMessageSeparatorString('</span><span class="help-block">')
                                                            ->setMessageCloseString('</span>')
                                                            ->render($element);
                                                    ?>

                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                              
                              
                                    </div>


                                <?php break; ?>
                    
                            <?php case "textarea": ?>

                     
                                    <div class="row">
                              

                                    <div class="col-lg-12 col-md-12 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>

                                            <div class="col-lg-10 col-md-10">
                                                <?php echo $this->formElement($element); ?>
                                                <?php if ($element->getOption('description')): ?>
                                                    <p class="help-block"><?php echo $element->getOption('description') ?></p>
                                                <?php endif; ?>
                                                <?php if ($this->formElementErrors($element)) : ?>
                                                    <?php
                                                    // Imprimo los errores
                                                    echo $this->formElementErrors()
                                                            ->setMessageOpenFormat('<span class="help-block">')
                                                            ->setMessageSeparatorString('</span><span class="help-block">')
                                                            ->setMessageCloseString('</span>')
                                                            ->render($element);
                                                    ?>

                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                             
                                    </div>


                                <?php break; ?>
                    
<?php case "checkbox": ?>



                                <?php break; ?>

                            <?php default: ?>

                                <?php if (($countRow % $multiplo) == 0): ?>
                                    <div class="row">
                                    <?php endif; ?>

                                    <div class="col-lg-6 col-md-6 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-4 col-md-4 control-label"><?php echo $element->getLabel() ?></label>

                                            <div class="col-lg-8 col-md-8">
                                                <?php echo $this->formElement($element); ?>
                                                <?php if ($element->getOption('description')): ?>
                                                    <p class="help-block"><?php echo $element->getOption('description') ?></p>
                                                <?php endif; ?>
                                                <?php if ($this->formElementErrors($element)) : ?>
                                                    <?php
                                                    // Imprimo los errores
                                                    echo $this->formElementErrors()
                                                            ->setMessageOpenFormat('<span class="help-block">')
                                                            ->setMessageSeparatorString('</span><span class="help-block">')
                                                            ->setMessageCloseString('</span>')
                                                            ->render($element);
                                                    ?>

                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php $countRow++; ?>
                                    <?php if (($countRow % $multiplo) == 0): ?>
                                    </div>
                                <?php endif; ?>

                                <?php break; ?>
                        <?php endswitch; ?>

                    <?php endforeach; ?>
                    
                     <div class="row">
                         
                        
                         
                         <?php $element =  $this->form->get('caba'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                          <?php $element =  $this->form->get('vicenteLopez'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                       <?php $element =  $this->form->get('Olivos'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                          <?php $element =  $this->form->get('Martinez'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                    
                      </div>
                    
                     
                     <div class="row">
                           <?php $element =  $this->form->get('Pilar'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                       <?php $element =  $this->form->get('SanIsidro'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                          <?php $element =  $this->form->get('BellaVista'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                         
                            <?php $element =  $this->form->get('iedad'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                          </div>
                    
                       <?php $element =  $this->form->get('rebound'); ?>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                                        <div  class=" form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
                                            <label class="col-lg-9 col-md-9 control-label"><?php echo $element->getLabel() ?></label>
                                            <div class="col-lg-3 col-md-3">
                                                <?php echo $this->formElement($element); ?>
                                            </div>
                                        </div>
                                    </div>
                          </div>
                    
                       <?php 
                       $element = $this->form->get('submit');
                       $element->setAttribute('class', 'btn btn-default'); ?>
                                <div class="col-lg-12 col-md-12">
                                    <?php echo $this->formElement($element); ?>
                                </div>
                    
                </div>
                <?php echo $this->form()->closeTag($form); ?>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('[name="fromDate"]').datetimepicker({
            pickTime: false,
            language: 'es'
        });

        $('[name="toDate"]').datetimepicker(
                {
                    pickTime: false,
                    language: 'es'
                });
    });
</script>
