

<?php
$form = $this->form;
$form->prepare();
//$form->setAttribute('action', $this->url('application', array('action' => 'edit')))->prepare();
echo $this->form()->openTag($form);
?>

<?php foreach ($form as $element) : ?>
<?php if ('hidden' == $element->getAttribute('type')):?>
  <?php echo $this->formElement($element); ?>
  <?php else: ?>
 
    <div class="col-lg-12">
        
        <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
            <?php if ('submit' != $element->getAttribute('type')) { ?>
                <label class="col-lg-3 control-label"><?php echo $element->getLabel() ?></label>
                <?php
                $element->setAttribute('class', 'form-control')
                        ->setAttribute('placeholder', $element->getLabel());
            } else {
                $element->setAttribute('class', 'btn btn-success');
            }
            ?>
            <div class="col-lg-9">
                <?php echo $this->formElement($element); ?>

               
            </div>
        </div>
    </div>
<?php endif; ?>
 


<?php endforeach; ?>
<?php echo $this->form()->closeTag($form); ?>
