<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/css/sb-admin-2.css')
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/font-awesome-4.2.0/css/font-awesome.css')
        ->appendStylesheet($this->basePath() . '/css/custom.css')
        ->appendStylesheet($this->basePath() . '/lib/datetimepicker/css/bootstrap-datetimepicker.min.css')
?> 