<?php

namespace Proxy\__CG__\Iem\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ScheduleSendingEmail extends \Iem\Entity\ScheduleSendingEmail implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getDatetimeFinish()
    {
        $this->__load();
        return parent::getDatetimeFinish();
    }

    public function setDatetimeFinish(\DateTime $datetimeFinish)
    {
        $this->__load();
        return parent::setDatetimeFinish($datetimeFinish);
    }

    public function getEstimatedEndingtime()
    {
        $this->__load();
        return parent::getEstimatedEndingtime();
    }

    public function setEstimatedEndingtime($estimatedEndingtime)
    {
        $this->__load();
        return parent::setEstimatedEndingtime($estimatedEndingtime);
    }

    public function getDatetimeSchedule()
    {
        $this->__load();
        return parent::getDatetimeSchedule();
    }

    public function setDatetimeSchedule(\DateTime $datetimeSchedule)
    {
        $this->__load();
        return parent::setDatetimeSchedule($datetimeSchedule);
    }

    public function getSmtp()
    {
        $this->__load();
        return parent::getSmtp();
    }

    public function setSmtp($smtp)
    {
        $this->__load();
        return parent::setSmtp($smtp);
    }

    public function getGroupingTemplate()
    {
        $this->__load();
        return parent::getGroupingTemplate();
    }

    public function setGroupingTemplate($groupingTemplate)
    {
        $this->__load();
        return parent::setGroupingTemplate($groupingTemplate);
    }

    public function getTimeInterval()
    {
        $this->__load();
        return parent::getTimeInterval();
    }

    public function setTimeInterval($timeInterval)
    {
        $this->__load();
        return parent::setTimeInterval($timeInterval);
    }

    public function getMailingListManager()
    {
        $this->__load();
        return parent::getMailingListManager();
    }

    public function setMailingListManager($mailingListManager)
    {
        $this->__load();
        return parent::setMailingListManager($mailingListManager);
    }

    public function getSendingList()
    {
        $this->__load();
        return parent::getSendingList();
    }

    public function setSendingList($sendingList)
    {
        $this->__load();
        return parent::setSendingList($sendingList);
    }

    public function getTimeIntervalTotal()
    {
        $this->__load();
        return parent::getTimeIntervalTotal();
    }

    public function setTimeIntervalTotal($timeIntervalTotal)
    {
        $this->__load();
        return parent::setTimeIntervalTotal($timeIntervalTotal);
    }

    public function getEmailsProcessed()
    {
        $this->__load();
        return parent::getEmailsProcessed();
    }

    public function setEmailsProcessed($emailsProcessed)
    {
        $this->__load();
        return parent::setEmailsProcessed($emailsProcessed);
    }

    public function getEmailsSent()
    {
        $this->__load();
        return parent::getEmailsSent();
    }

    public function setEmailsSent($emailsSent)
    {
        $this->__load();
        return parent::setEmailsSent($emailsSent);
    }

    public function getEmailsFailed()
    {
        $this->__load();
        return parent::getEmailsFailed();
    }

    public function setEmailsFailed($emailsFailed)
    {
        $this->__load();
        return parent::setEmailsFailed($emailsFailed);
    }

    public function getEmailsPending()
    {
        $this->__load();
        return parent::getEmailsPending();
    }

    public function setEmailsPending($emailsPending)
    {
        $this->__load();
        return parent::setEmailsPending($emailsPending);
    }

    public function getEmailsTotal()
    {
        $this->__load();
        return parent::getEmailsTotal();
    }

    public function setEmailsTotal($emailsTotal)
    {
        $this->__load();
        return parent::setEmailsTotal($emailsTotal);
    }

    public function getCombination()
    {
        $this->__load();
        return parent::getCombination();
    }

    public function setCombination($combination)
    {
        $this->__load();
        return parent::setCombination($combination);
    }

    public function getScheduleEmailControl()
    {
        $this->__load();
        return parent::getScheduleEmailControl();
    }

    public function setScheduleEmailControl($scheduleEmailControl)
    {
        $this->__load();
        return parent::setScheduleEmailControl($scheduleEmailControl);
    }

    public function getEmailLayout()
    {
        $this->__load();
        return parent::getEmailLayout();
    }

    public function setEmailLayout($emailLayout)
    {
        $this->__load();
        return parent::setEmailLayout($emailLayout);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getCreatedBy()
    {
        $this->__load();
        return parent::getCreatedBy();
    }

    public function setCreatedBy($createdBy)
    {
        $this->__load();
        return parent::setCreatedBy($createdBy);
    }

    public function getLastUpdatedBy()
    {
        $this->__load();
        return parent::getLastUpdatedBy();
    }

    public function setLastUpdatedBy($lastUpdatedBy)
    {
        $this->__load();
        return parent::setLastUpdatedBy($lastUpdatedBy);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function toArray($object = NULL)
    {
        $this->__load();
        return parent::toArray($object);
    }

    public function fromArray(array $data)
    {
        $this->__load();
        return parent::fromArray($data);
    }

    public function __call($method, $args)
    {
        $this->__load();
        return parent::__call($method, $args);
    }

    public function __get($property)
    {
        $this->__load();
        return parent::__get($property);
    }

    public function __set($property, $value)
    {
        $this->__load();
        return parent::__set($property, $value);
    }

    public function exchangeArray(array $data)
    {
        $this->__load();
        return parent::exchangeArray($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'datetimeSchedule', 'datetimeFinish', 'timeInterval', 'timeIntervalTotal', 'state', 'emailsProcessed', 'emailsSent', 'emailsFailed', 'emailsPending', 'emailsTotal', 'estimatedEndingtime', 'combination', 'createdAt', 'updatedAt', 'mailingListManager', 'smtp', 'groupingTemplate', 'sendingList', 'scheduleEmailControl', 'emailLayout', 'createdBy', 'lastUpdatedBy');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}